### PR TITLE
Manual bump test

### PR DESCRIPTION
**Pull request by mihaisc**
Bumped ocean.js and  @graphprotocol/graph-cli.
Updated git actions to node 16.

### CODE REVIEW

**Comment by mihaisc** [comment]
I'm currently stuck. Tests run ok locally. Not sure exactly why the subgraph is not deployed properly in github actions, in theory nothing should have changed with these dependencies.
In the initial setup of the tests some run commands were run in parallel and `npm run deploy`  was run before `npm run create`.

**Comment by kremalicious** [comment]
Does this help? Ran into some GitHub Actions specific issue with our address file env vars: https://github.com/oceanprotocol/ocean.js/blob/main/.github/workflows/ci.yml#L88-L91

**Comment by mihaisc** [comment]
address  seems ok here, we kinda put it everywhere, so it not that

**Comment by alexcos20** [comment]
found the problem.
 - with graph-cli  0.18.0 works like a charm
 - with graph-cli 0.21.X , it breaks..

**Comment by kremalicious** [comment]
Haha, so seems we did find another project using minor version bumps for major changes

**Review by alexcos20 — APPROVED** [review]

**Pull request merged**
