### PR TITLE
add dispenser

### LINKED ISSUE #90: Free pricing
See [EPIC ](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/91) for details

### PR DESCRIPTION
**Pull request by alexcos20**
Closes #90

### CODE REVIEW

**Comment by alexcos20** [comment]
waiting for a new ocean.js, in order to have tests as well

**Comment by jamiehewitt15** [comment]
I tried running it locally with Barge but I got an error, Let me know if I did anything wrong, I ran:
```
npm install
export ADDRESS_FILE="${HOME}/.ocean/ocean-contracts/artifacts/address.json"
npm run bargesetup
npm run create:local-barge
npm run deploy:local-barge
```
Barge is running in a separate terminal with `./start_ocean.sh --with-thegraph`

**Comment by mihaisc** [comment]
FIxed now. 
@jamiehewitt15 there was one step missing, exporting the address file (it was updated in main).

**Comment by jamiehewitt15** [comment]
> FIxed now.
> @jamiehewitt15 there was one step missing, exporting the address file (it was updated in main). You are missing npm run codegen as well.
> Need to fix the tests

Thanks, I'll test it again

**Comment by jamiehewitt15** [comment]
Seems to work well now. By the way, I added the `npm run codegen` command to the readme in the instructions for running it on Barge

**Comment by jamiehewitt15** [comment]
It seems like the tests are failing slightly randomly, I have run them a couple of times locally and they pass sometimes but not all the time. The sleep time may need to be increased

**Comment by mihaisc** [comment]
@jamiehewitt15 yep, it depends on what resources the graph has. I increased all sleep times, hopefully 3 seconds is enough

**Comment by mihaisc** [comment]
Ready from my point of view. @alexcos20 remove the WIP label if no more work is needed here.

**Review by jamiehewitt15 — APPROVED** [review]

**Comment by jamiehewitt15** [comment]
Seems ok to me too, I have approved

**Pull request merged**
