### PR TITLE
remove MetadataCreated from metadataUpdate

### PR DESCRIPTION
**Pull request by alexcos20**
Removes MetadataCreated  from metadataUpdate

### CODE REVIEW

**Review by kremalicious — APPROVED** [review]
good from `market` side I think. It doesn't break things if the `createTime` & `tx` entry are not affected, we use those for showing the creation entry https://github.com/oceanprotocol/market/blob/main/src/components/organisms/AssetContent/EditHistory.tsx#L13

**Comment by ssallam** [comment]
I don't think this is right approach.  previously you had a complete picture of the metadata history.
I don't understand why is this a problem in the UI?

**Comment by ssallam** [comment]
also if we don't want the create event, then we can remove it from the `eventHandlers` in the `subgraph.yaml` file.

**Comment by ssallam** [comment]
> good from `market` side I think. It doesn't break things if the `createTime` & `tx` entry are not affected, we use those for showing the creation entry https://github.com/oceanprotocol/market/blob/main/src/components/organisms/AssetContent/EditHistory.tsx#L13

note that create time of metadata is not necessarily the same as that of the datatoken.

**Comment by kremalicious** [comment]
Yes, this then sounds like a frontend problem. Sounds like the UI should always assume that the very first item within `updates` is the creation transaction, and assume that it only has been updated if there are more than 2 items. When looking at the code in https://github.com/oceanprotocol/market/blob/main/src/components/organisms/AssetContent/EditHistory.tsx#L13 it was assumed that `updates` only contains updates after the creation, hence the additional query for `createTime` & `tx`

**Comment by mihaisc** [comment]
Put this on hold please, we need some time to think this through. Considering all the comments maybe these changes aren't needed, and we modify the UI. We have other priorities now on the market.

**Pull request closed without merging**
