### PR TITLE
CI tweaks

### PR DESCRIPTION
**Pull request by kremalicious**
- run all jobs as one workflow, less clicking around between 2 workflows when checking out runs
- remove duplicate test runs for each PR, as it was set to run for each PR AND push
- fix multiple issues for fresh installs
- new `package-lock.json` generated from scratch

### CODE REVIEW

**Comment by mihaisc** [comment]
why do we need this?  it's not working on node 14 ,and probably won't work on macos and windows , we don't support those and we don't really need to.  
Agree with removing duplication

**Comment by mihaisc** [comment]
Did you use node 16?

**Comment by mihaisc** [comment]
That error is from the graph cli, not sure what fixed it. I'll try to update to the new version in another pr.

**Comment by kremalicious** [comment]
good CI setup changes but integration tests because of updated graph-cli are a mess so we don't need to bother right now. Can be used for a new PR once graph-cli is in better shape

**Pull request closed without merging**
