### PR TITLE
nft transfer event

### LINKED ISSUE #570: NFT Transfer event and related entity not persisted in subgraph and not queryable
**Is your feature request related to a problem? Please describe.**
NFT Transfer event are not queryable from GraphQL queries.
token, order or other entities unable to access history of previous/pass owner.

**Describe the solution you'd like**
Subgraph to index transfer event for existing assets.
Token entity to have list of previous/pass owner.

**Additional context**
So that we able to:
1. Trace the pass owner after very long time, maybe 1 year in the pass.
2. Consolidate the orders and number of orders under specific owner of specific duration for specific asset (through multiple query if needed to).

@jamiehewitt15 this is the topic we talk about last week (week 45, 2022)

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #570 

Changes proposed in this PR:

- Tracking `NftTransferHistory`
- Updating `creator`, `owner` and `transferHistory` in `Order`
- Updating tests

### CODE REVIEW

**Comment by alexcos20** [comment]
looks good so far, see https://github.com/oceanprotocol/aquarius/pull/943

**Comment by soonhuat** [comment]
@jamiehewitt15 did I miss anything?
I thought order entity will also store nftOwner on entitycreation?

**Comment by jamiehewitt15** [comment]
> @jamiehewitt15 did I miss anything? I thought order entity will also store nftOwner on entity creation?

Yeah, I had it in initially but removed it due to Alex's [comment](https://github.com/oceanprotocol/ocean-subgraph/pull/573#discussion_r1027857872) above. Let me know if you need it and I'll add it back in

**Comment by alexcos20** [comment]
We already have it:

https://github.com/oceanprotocol/ocean-subgraph/blob/1bf645541fbc4292b38568db76f7cf79c44cf002/schema.graphql#L152
https://github.com/oceanprotocol/ocean-subgraph/blob/1bf645541fbc4292b38568db76f7cf79c44cf002/src/mappings/erc20Templates.ts#L44

**Comment by alexcos20** [comment]
Looks like we don't have them :)
I will push soon

**Comment by alexcos20** [comment]
> > @jamiehewitt15 did I miss anything? I thought order entity will also store nftOwner on entity creation?
> 
> Yeah, I had it in initially but removed it due to Alex's [comment](https://github.com/oceanprotocol/ocean-subgraph/pull/573#discussion_r1027857872) above. Let me know if you need it and I'll add it back in

I was under the impression that nftOwner was under nftData, and not Order.  that's why I said that we don't need it.  my  mistake, sorry

**Comment by jamiehewitt15** [comment]
> > > @jamiehewitt15 did I miss anything? I thought order entity will also store nftOwner on entity creation?
> > 
> > 
> > Yeah, I had it in initially but removed it due to Alex's [comment](https://github.com/oceanprotocol/ocean-subgraph/pull/573#discussion_r1027857872) above. Let me know if you need it and I'll add it back in
> 
> I was under the impression that nftOwner was under nftData, and not Order. that's why I said that we don't need it. my mistake, sorry

No worries, I've added it back in

**Review by alexcos20 — APPROVED** [review]

**Pull request merged**
