### PR TITLE
add token name symbol to pools

### LINKED ISSUE #13: poolId.tokens.tokenId.symbol is always null for OCEAN
For a query [like this](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolShares(orderBy%3Abalance%2CorderDirection%3A%20desc%2C%20first%3A%201000%2C%20where%3A%20%7BuserAddress%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20balance%0A%20%20%20%20userAddress%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20poolId%20%7B%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20tokenId%20%7B%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) when trying to get the symbols of the tokens within a pool, the OCEAN one is always `null`

### PR DESCRIPTION
**Pull request by alexcos20**
Closes #13 

Changes proposed in this PR:

- add token name to pool tokens
- add token symbol to pool tokens

try it local with:  [query](http://127.0.0.1:8000/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolShares(orderBy%3Abalance%2CorderDirection%3A%20desc%2C%20first%3A%201000%2C%20where%3A%20%7BuserAddress%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20balance%0A%20%20%20%20userAddress%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20poolId%20%7B%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20tokenAddress%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20tokenId%20%7B%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) 

Expected result:

```
{
        "balance": "100",
        "id": "0xa5342efad4ddd66dabb095ee2db4bd272d54445e-0x4d156a2ef69ffddc55838176c6712c90f60a2285",
        "poolId": {
          "tokens": [
            {
              "name": "Boorish Oyster Token",
              "symbol": "BOOOYS-26",
              "tokenAddress": "0x1d9a0ad91a5bd3d4091fd474c481a3079a846260",
              "tokenId": {
                "address": "0x1d9a0ad91a5bd3d4091fd474c481a3079a846260",
                "symbol": "BOOOYS-26"
              }
            },
            {
              "name": "OceanToken",
              "symbol": "OCEAN",
              "tokenAddress": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
              "tokenId": null
            }
          ]
        },
        "userAddress": {
          "id": "0x4d156a2ef69ffddc55838176c6712c90f60a2285"
        }
      },
```

Questions:  should we rename tokenId to datatokenId ?
If tokenId is null, then that token is not a datatoken

### CODE REVIEW

**Comment by kremalicious** [comment]
It seems everything under `tokenId` is just redundant? `name`, `symbol`, `address` is all there already. I would ditch the `token` prefix for keys for everything under `tokens[]`, cause also redundant. If we want to signal which one is a datatoken then something like `isDatatoken` would be way more clear.

And just double checking, the `name` for OCEAN will appear as `Ocean Token` (with space), right?

**Comment by alexcos20** [comment]
sure, it makes sense to keep only address/symbol, as long as it is not breaking something (@idiom-bytes - is it ok from Dao/Snapsot side?)

**Comment by alexcos20** [comment]
regarding symbol/names - it will fetch whatever is in the contract for symbol/names.  Mainnet is with space, rinkeby without :)

**Comment by kremalicious** [comment]
oh, interesting, so we never redeployed our token contract in the testnets as we did multiple times in mainnet. So the testnets do not reflect current token contract but guess this has no real implication https://github.com/oceanprotocol/token/blob/master/contracts/OceanToken.sol#L33

**Comment by alexcos20** [comment]
> oh, interesting, so we never redeployed our token contract in the testnets as we did multiple times in mainnet. So the testnets do not reflect current token contract but guess this has no real implication https://github.com/oceanprotocol/token/blob/master/contracts/OceanToken.sol#L33

indeed, we have only the old versions.

**Comment by alexcos20** [comment]
new layout:
````
poolShares": [
      {
        "balance": "100",
        "id": "0xa5342efad4ddd66dabb095ee2db4bd272d54445e-0x4d156a2ef69ffddc55838176c6712c90f60a2285",
        "poolId": {
          "tokens": [
            {
              "address": "0x1d9a0ad91a5bd3d4091fd474c481a3079a846260",
              "isDatatoken": true,
              "name": "Boorish Oyster Token",
              "symbol": "BOOOYS-26"
            },
            {
              "address": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
              "isDatatoken": false,
              "name": "OceanToken",
              "symbol": "OCEAN"
            }
          ]
        },
        "userAddress": {
          "id": "0x4d156a2ef69ffddc55838176c6712c90f60a2285"
        }
      },
      {
        "balance": "4.108596132489867437",
        "id": "0x18badbad531d05c8a8e7d8c3493ef9136d51430b-0x4d156a2ef69ffddc55838176c6712c90f60a2285",
        "poolId": {
          "tokens": [
            {
              "address": "0x8921f0f2bce1293772c4f091ebeda4d25eef024a",
              "isDatatoken": true,
              "name": "Sartorial Seagull Token",
              "symbol": "SARSEA-13"
            },
            {
              "address": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
              "isDatatoken": false,
              "name": "OceanToken",
              "symbol": "OCEAN"
            }
          ]
        },
        "userAddress": {
          "id": "0x4d156a2ef69ffddc55838176c6712c90f60a2285"
        }
      }
    ]
```

Maybe we should add decimals as well?

**Comment by kremalicious** [comment]
decimals is good idea, useful if we want to have more add token to metamask buttons

**Comment by alexcos20** [comment]
done
```
{
        "balance": "100",
        "id": "0xa5342efad4ddd66dabb095ee2db4bd272d54445e-0x4d156a2ef69ffddc55838176c6712c90f60a2285",
        "poolId": {
          "tokens": [
            {
              "address": "0x1d9a0ad91a5bd3d4091fd474c481a3079a846260",
              "decimals": 18,
              "isDatatoken": true,
              "name": "Boorish Oyster Token",
              "symbol": "BOOOYS-26"
            },
            {
              "address": "0x8967bcf84170c91b0d24d4302c2376283b0b3a07",
              "decimals": 18,
              "isDatatoken": false,
              "name": "OceanToken",
              "symbol": "OCEAN"
            }
          ]
        },
        "userAddress": {
          "id": "0x4d156a2ef69ffddc55838176c6712c90f60a2285"
        }
      }
```

**Comment by kremalicious** [comment]
as far as I can see this is a breaking change for market, but only on the History page:
https://github.com/oceanprotocol/market/blob/main/src/components/pages/History/PoolShares.tsx#L29

So if we want to deploy it it we need to prepare a small market update first

**Comment by alexcos20** [comment]
ok, let's keep it on hold.
also @idiom-bytes , please check on your side as well

**Review by kremalicious — APPROVED** [review]
awesome, now much easier to solve https://github.com/oceanprotocol/market/issues/456

**Comment by idiom-bytes** [comment]
Hey guys,

As far as I can see, the only thing added was the token[{name, symbol}], in addition to the redundant bits that were removed.

Our pools query does not look into any of this data, so I don't think this will have an impact on the strategy (which isn't quite working yet).

For reference, this is the GQL query into DT pools.

I'm approving this PR.

```
{
pools (first: 1000, orderBy: oceanReserve, orderDirection: desc) {
  id,
  holderCount,
  oceanReserve,
  active,
  totalShares,
  shares (first: 1000) {
    id,
    userAddress {
      id,
      tokensOwned {
        id
      }
    },
    balance
  },
  tokens {
    balance,
    denormWeight,
    tokenId {
      id
    }
  }
}
}
```

**Comment by alexcos20** [comment]
```
 tokens {
    balance,
    denormWeight,
    tokenId {
      id
    }
  }
```

tokenId was removed.   you need to replace it probably with "address"

**Comment by idiom-bytes** [comment]
I think you mean "tokenAddress".

We'll update the strategy.

**Comment by kremalicious** [comment]
this is the actual change: https://github.com/oceanprotocol/ocean-subgraph/pull/61/files#diff-efc1675187620595b0844197a25c35eac9b6df752f9182e5cffddee6f27a8489

So instead of:

```graphql
tokens {
    balance,
    denormWeight,
    tokenId {
      id
    }
  }
```

after this change is deployed it should be like this:

```graphql
tokens {
    balance,
    denormWeight,
    address
  }
```

As for market, was quick change. Think we get our auto-generated typings from the Rinkeby subgraph so that PR build might succeed when it's deployed on Rinkeby. Otherwise we kinda have to deploy to Mainnet to make PR build succeed

**Comment by idiom-bytes** [comment]
As I mentioned to Alex, the strategy isn't quite working so this won't break anything.

I'll have a new GQL ready to go, and will test once the Rinkeby/Mainnet subgraph is available.

**Comment by alexcos20** [comment]
@kremalicious @mihaisc - 2nd graph deployed and it's live.
check [query](https://subgraph2.mainnet.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=%7B%0A%20%20poolShares(orderBy%3Abalance%2CorderDirection%3A%20desc%2C%20first%3A%201000%2C%20where%3A%20%7BuserAddress%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20balance%0A%20%20%20%20userAddress%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20poolId%20%7B%0A%20%20%20%20%20%20tokens%20%7B%0A%20%20%20%20%20%20%20%20address%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20isDatatoken%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Pull request merged**
