### PR TITLE
Storing the fraction of veOcean

### LINKED ISSUE #622: Fix ve delegation calculations
Subgraph records the delegated veOCEAN amount. We should be recording the percentage delegated instead.
Ticket reopened until everything is deployed and running in mainnet

```
curVeOcean = getVeOceanBalance(_delegator)
pctDelegated = _amount / curVeOcean
```

Order of blockers:
1. Subgraph mainnet is not deployed because goerli isn't quite signed off.
2. Norbert is stuck because subgraph mainnet is not deployed.

#DoD:
- [x] Subgraph goerli has the veDelegate and the right schema (https://v4.subgraph.goerli.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql)

### PR DESCRIPTION
**Pull request by jamiehewitt15**
Fixes #622 

Changes proposed in this PR:

- Saving the percentage of veOcean that is delegated

### CODE REVIEW

**Comment by mihaisc** [comment]
please add moment in package.json as devDep so the tests pass

**Comment by idiom-bytes** [comment]
Dependency on https://github.com/oceanprotocol/df-web/pull/492

**Comment by mihaisc** [comment]
Unblocked multichain fix was merged in main

**Comment by jamiehewitt15** [comment]
> Unblocked, multichain fix was merged in main

Awesome, thanks a lot

**Comment by jamiehewitt15** [comment]
> Unblocked, multichain fix was merged in main

Are you sure about this? Two tests are still failing (related to the timestamp) and right now the changes on this PR are commented out 🤔

**Review by mihaisc — APPROVED** [review]

**Comment by idiom-bytes** [comment]
@mihaisc tests are failing on the following, can you take a look?
```
1) Make sure that graph has synced to last block
```

**Pull request merged**
